blank_issues_enabled: true
contact_links:
  - name: If you have questions, use the discussions
    url: https://github.com/CaptainPowerTurtle/terraform-hcloud-kube-hetzner-rke2/discussions
    about: Please ask and answer questions here.